name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: garyedwardhughes/ubuntu-stddecimal
    steps:
    - uses: actions/checkout@v2
    - name: Build Clang
      run: ln -s /IntelRDFPMathLib20U2 .. && LD_LIBRARY_PATH=/usr/local/lib ./build_clang.sh all test
