name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: garyedwardhughes/ubuntu-stddecimal
    steps:
    - uses: actions/checkout@v2
    - name: Build Clang
      run: |
        ln -s /IntelRDFPMathLib20U2 .. 
        ln -s /IntelRDFPMathLib20U2/LIBRARY/gcc000libbid.a /IntelRDFPMathLib20U2/LIBRARY/libbid.a 
        LD_LIBRARY_PATH=/usr/local/lib ./build_clang.sh all test
        # Make this easy to find regardless of build type which changes the path.
        ln -s `find . -type f -name test_runner`
    
    - name: test subset decimal32
      run: ./test_runner --bits 32 general_decimal_arithmetic/tests/subset/* > subset_32_results.md.
